### ISSUE TITLE
build error after installing v1.120.1

### ISSUE THREAD

**Issue by sfinnie** [abstratt/textuml#74]
Problem as described in [this thread(https://groups.google.com/forum/#!topic/textuml-toolkit/v5nbbMirV0Y), log output as follows:

`!SESSION 2015-06-04 14:48:57.613 -----------------------------------------------
eclipse.buildId=4.4.2.M20150204-1700
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_GB
Framework arguments:  -product org.eclipse.epp.package.dsl.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.dsl.product

!ENTRY org.eclipse.egit.ui 2 0 2015-06-04 14:49:10.673
!MESSAGE Warning: EGit couldn't detect the installation path "gitPrefix" of native Git. Hence EGit can't respect system level
Git settings which might be configured in ${gitPrefix}/etc/gitconfig under the native Git installation directory.
The most important of these settings is core.autocrlf. Git for Windows by default sets this parameter to true in
this system level configuration. The Git installation location can be configured on the
Team > Git > Configuration preference page's 'System Settings' tab.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.egit.ui 2 0 2015-06-04 14:49:10.688
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\sfinnie'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.core.resources 4 2 2015-06-04 14:49:13.765
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoClassDefFoundError: com/abstratt/pluginutils/ISharedContextRunnable
	at com.abstratt.mdd.frontend.core.FrontEnd.getCompilationDirector(FrontEnd.java:27)
	at com.abstratt.mdd.frontend.internal.ui.VerySimpleBuilder.build(VerySimpleBuilder.java:65)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.ClassNotFoundException: com.abstratt.pluginutils.ISharedContextRunnable cannot be found by com.abstratt.mdd.frontend.core_1.120.1.201506041326
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

!ENTRY org.eclipse.core.resources 4 75 2015-06-04 14:49:13.780
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 com.abstratt.mdd.frontend.ui 4 75 2015-06-04 14:49:13.780
!MESSAGE Errors running builder 'MDD Front-end Builder' on project 'HelloTextUML'.
!STACK 0
java.lang.NoClassDefFoundError: com/abstratt/pluginutils/ISharedContextRunnable
	at com.abstratt.mdd.frontend.core.FrontEnd.getCompilationDirector(FrontEnd.java:27)
	at com.abstratt.mdd.frontend.internal.ui.VerySimpleBuilder.build(VerySimpleBuilder.java:65)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.ClassNotFoundException: com.abstratt.pluginutils.ISharedContextRunnable cannot be found by com.abstratt.mdd.frontend.core_1.120.1.201506041326
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

!ENTRY org.eclipse.core.resources 4 2 2015-06-04 14:49:50.776
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoClassDefFoundError: com/abstratt/pluginutils/ISharedContextRunnable
	at com.abstratt.mdd.frontend.core.FrontEnd.getCompilationDirector(FrontEnd.java:27)
	at com.abstratt.mdd.frontend.internal.ui.VerySimpleBuilder.build(VerySimpleBuilder.java:65)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.ClassNotFoundException: com.abstratt.pluginutils.ISharedContextRunnable cannot be found by com.abstratt.mdd.frontend.core_1.120.1.201506041326
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more

!ENTRY org.eclipse.core.resources 4 75 2015-06-04 14:49:50.792
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 com.abstratt.mdd.frontend.ui 4 75 2015-06-04 14:49:50.792
!MESSAGE Errors running builder 'MDD Front-end Builder' on project 'HelloTextUML'.
!STACK 0
java.lang.NoClassDefFoundError: com/abstratt/pluginutils/ISharedContextRunnable
	at com.abstratt.mdd.frontend.core.FrontEnd.getCompilationDirector(FrontEnd.java:27)
	at com.abstratt.mdd.frontend.internal.ui.VerySimpleBuilder.build(VerySimpleBuilder.java:65)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.ClassNotFoundException: com.abstratt.pluginutils.ISharedContextRunnable cannot be found by com.abstratt.mdd.frontend.core_1.120.1.201506041326
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
`

**Comment by abstratt** [comment]
Thanks, @sfinnie. I think this was due to a weakly specified dependency, which allowed the TextUML Toolkit to run with an older version (1.9.0.xxx) of the com.abstratt.pluginutils plug-in, which did not have the ISharedContextRunnable API yet.

I think this was fixed in commit 0c148dc. You should not have to uninstall the TextUML Toolkit or EclipseGraphviz. Checking for updates should offer a new build (same version, different timestamp) that has the fix.

Please let me know if this does not fix the issue.

**Comment by abstratt** [comment]
Just tried it, introduced another dependency issue...

**Comment by abstratt** [comment]
Commit 72b144393d6dede8b822e397d1ccf26fd1eefb1f addresses that second issue (dependencies on org.apache.commons... not being resolved.
