### ISSUE TITLE
Graphviz illegalArgumentException

### ISSUE THREAD

**Issue by simonjwright** [abstratt/textuml#94]
Just installed 2.1.201501.201602190029 over a new Mars (Modelling).

The image viewer displays an empty class OK, but if I add an attribute I get an exception.

eclipse.buildId=4.5.1.M20150904-0015
java.version=1.8.0_66
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.modeling.product -product org.eclipse.epp.package.modeling.product
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.modeling.product -data file:/Users/simon/eclipse/workspace/ -product org.eclipse.epp.package.modeling.product

java.lang.IllegalArgumentException: No enum constant com.abstratt.mdd.modelrenderer.uml2dot.UML2DOTPreferences.ShowMinimumVisibilityOptions.
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.abstratt.mdd.modelrenderer.RenderingSettings.getSelection(RenderingSettings.java:40)
	at com.abstratt.mdd.modelrenderer.uml2dot.RendererHelper.shouldSkip(RendererHelper.java:12)
	at com.abstratt.mdd.modelrenderer.uml2dot.PropertyRenderer.renderObject(PropertyRenderer.java:20)
	at com.abstratt.mdd.modelrenderer.uml2dot.PropertyRenderer.renderObject(PropertyRenderer.java:1)
	at com.abstratt.mdd.modelrenderer.RenderingSession.render(RenderingSession.java:62)
	at com.abstratt.mdd.modelrenderer.RenderingUtils.lambda$0(RenderingUtils.java:10)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.abstratt.mdd.modelrenderer.RenderingUtils.renderAll(RenderingUtils.java:10)
	at com.abstratt.mdd.modelrenderer.uml2dot.ClassifierRenderer.lambda$9(ClassifierRenderer.java:77)
	at com.abstratt.mdd.modelrenderer.IndentedPrintWriter.runInNewLevel(IndentedPrintWriter.java:60)
	at com.abstratt.mdd.modelrenderer.uml2dot.ClassifierRenderer.lambda$5(ClassifierRenderer.java:76)
	at com.abstratt.mdd.modelrenderer.IndentedPrintWriter.runInNewLevel(IndentedPrintWriter.java:60)
	at com.abstratt.mdd.modelrenderer.uml2dot.ClassifierRenderer.lambda$3(ClassifierRenderer.java:73)
	at com.abstratt.mdd.modelrenderer.IndentedPrintWriter.runInNewLevel(IndentedPrintWriter.java:60)
	at com.abstratt.mdd.modelrenderer.uml2dot.ClassifierRenderer.lambda$0(ClassifierRenderer.java:42)
	at com.abstratt.mdd.modelrenderer.IndentedPrintWriter.runInNewLevel(IndentedPrintWriter.java:60)
	at com.abstratt.mdd.modelrenderer.uml2dot.ClassifierRenderer.renderObject(ClassifierRenderer.java:40)
	at com.abstratt.mdd.modelrenderer.uml2dot.ClassRenderer.renderObject(ClassRenderer.java:22)
	at com.abstratt.mdd.modelrenderer.uml2dot.ClassRenderer.renderObject(ClassRenderer.java:1)
	at com.abstratt.mdd.modelrenderer.uml2dot.ClassifierRenderer.renderObject(ClassifierRenderer.java:1)
	at com.abstratt.mdd.modelrenderer.RenderingSession.render(RenderingSession.java:62)
	at com.abstratt.mdd.modelrenderer.RenderingSession.render(RenderingSession.java:41)
	at com.abstratt.mdd.modelrenderer.uml2dot.PackageRenderer.lambda$1(PackageRenderer.java:25)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.abstratt.mdd.modelrenderer.uml2dot.PackageRenderer.renderObject(PackageRenderer.java:25)
	at com.abstratt.mdd.modelrenderer.uml2dot.PackageRenderer.renderObject(PackageRenderer.java:1)
	at com.abstratt.mdd.modelrenderer.RenderingSession.render(RenderingSession.java:62)
	at com.abstratt.mdd.modelrenderer.RenderingUtils.lambda$0(RenderingUtils.java:10)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.abstratt.mdd.modelrenderer.RenderingUtils.renderAll(RenderingUtils.java:10)
	at com.abstratt.mdd.modelrenderer.dot.DOTRendering.generateDOTFromModel(DOTRendering.java:78)
	at com.abstratt.mdd.modelrenderer.dot.DOTRendering.generateDOTFromModel(DOTRendering.java:49)
	at com.abstratt.mdd.modelrenderer.dot.DOTRendering.generateDOTFromModel(DOTRendering.java:34)
	at com.abstratt.mdd.modelviewer.AbstractModelGraphicalContentProvider.loadImage(AbstractModelGraphicalContentProvider.java:42)
	at com.abstratt.imageviewer.AbstractGraphicalContentProvider$ContentLoader.run(AbstractGraphicalContentProvider.java:81)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by abstratt** [comment]
@simonjwright Thanks, I am looking into it.

**Comment by abstratt** [comment]
@simonjwright The fix is in. When [build number 420](https://textuml.ci.cloudbees.com/job/textuml-toolkit/) is complete, if you updated, you should get the fix.

**Comment by abstratt** [comment]
@simonjwright Build is complete. Please give it a whirl. If after you update, things still don't look fixed, please reopen.

**Comment by simonjwright** [comment]
Looking good! Thanks very much
